name: Deploy website

# on: push

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build:qa

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: w330212.ferozo.com
          username: w330212
          password: Stardoc2024
          local-dir: ./dist/
          server-dir: public_html/ZambaDash/
